<?php
require_once 'UNL/Templates.php';
$p = UNL_Templates::factory('Fixed');
if (isset($_SERVER['UNL_TEMPLATEDEPENDENTSPATH'])):
    UNL_Templates::$options['templatedependentspath'] = '/srv/www/htdocs/';
endif;
$p->doctitle = "<title>UNL | pear.unl.edu | UNL_Services_Peoplefinder | Docs For Class UNL_Services_PeoplefinderTest</title>";
$p->breadcrumbs = '<ul>
                    <li><a href="http://www.unl.edu/">UNL</a></li>
                    <li><a href="http://pear.unl.edu/">pear.unl.edu</a></li>
                    <li><a href="http://pear.unl.edu/index.php?package=UNL_Services_Peoplefinder">UNL_Services_Peoplefinder</a></li>
                    <li>API Documentation</li>
                    </ul>';
$p->head .= '<link type="text/css" rel="stylesheet" href="/docs/UNL_Services_Peoplefinder/media/stylesheet.css" />';
$p->titlegraphic = '<h1>UNL_Services_Peoplefinder API Documentation</h1><h2>Developers, developers, developers, devel&hellip;</h2>';
$p->navlinks = file_get_contents($_SERVER['DOCUMENT_ROOT'].'/docs/UNL_Services_Peoplefinder/li_UNL_Services_Peoplefinder.php');
$p->leftRandomPromo = '';
ob_start();
?>
			<div class="page-body">			
<h2 class="class-name">Class UNL_Services_PeoplefinderTest</h2>

<a name="sec-description"></a>
<div class="info-box">
	<div class="info-box-title">Description</div>
	<div class="nav-bar">
					<span class="disabled">Description</span> |
													<a href="#sec-var-summary">Vars</a> (<a href="#sec-vars">details</a>)
						|											<a href="#sec-method-summary">Methods</a> (<a href="#sec-methods">details</a>)
						
					</div>
	<div class="info-box-body">
        		<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Test class for UNL_Services_Peoplefinder.</p>
<div class="description"><p>Generated by PHPUnit_Util_Skeleton on 2007-04-13 at 10:19:55.</p></div>
		<p class="notes">
			Located in <a class="field" href="_tests---UNL_Services_PeoplefinderTest.php.php">/tests/UNL_Services_PeoplefinderTest.php</a> (line <span class="field">28</span>)
		</p>
		
				
		<pre>PHPUnit_Framework_TestCase
   |
   --UNL_Services_PeoplefinderTest</pre>
	
			</div>
</div>



	<a name="sec-var-summary"></a>
	<div class="info-box">
		<div class="info-box-title">Variable Summary</div>
		<div class="nav-bar">
			<a href="#sec-description">Description</a> |
						<span class="disabled">Vars</span> (<a href="#sec-vars">details</a>)
							| 
									<a href="#sec-method-summary">Methods</a> (<a href="#sec-methods">details</a>)
							
								</div>
		<div class="info-box-body">
			<div class="var-summary">
																								<div class="var-title">
					<span class="var-type">mixed</span>
					<a href="#var_uid" title="details" class="var-name">$uid</a>
				</div>
											</div>
		</div>
	</div>

	<a name="sec-method-summary"></a>
	<div class="info-box">
		<div class="info-box-title">Method Summary</div>
		<div class="nav-bar">
			<a href="#sec-description">Description</a> |
																		<a href="#sec-var-summary">Vars</a> (<a href="#sec-vars">details</a>)
				 
				|
						<span class="disabled">Methods</span> (<a href="#sec-methods">details</a>)
		</div>
		<div class="info-box-body">			
			<div class="method-summary">
												<div class="method-definition">
					static 						<span class="method-result">void</span>
										<a href="#main" title="details" class="method-name">main</a>
										()
									</div>
																																																								
																				<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#setUp" title="details" class="method-name">setUp</a>
										()
									</div>
																<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#tearDown" title="details" class="method-name">tearDown</a>
										()
									</div>
																<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#testGetEmail" title="details" class="method-name">testGetEmail</a>
										()
									</div>
																<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#testGetFullName" title="details" class="method-name">testGetFullName</a>
										()
									</div>
																<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#testGetHCard" title="details" class="method-name">testGetHCard</a>
										()
									</div>
																<div class="method-definition">
											<span class="method-result">void</span>
										<a href="#testGetVCard" title="details" class="method-name">testGetVCard</a>
										()
									</div>
								</div>
		</div>
	</div>		

	<a name="sec-vars"></a>
	<div class="info-box">
		<div class="info-box-title">Variables</div>
		<div class="nav-bar">
			<a href="#sec-description">Description</a> |
										<a href="#sec-var-summary">Vars</a> (<span class="disabled">details</span>)
						
			
										| 
									<a href="#sec-method-summary">Methods</a> (<a href="#sec-methods">details</a>)
							
					</div>
		<div class="info-box-body">
			<a name="var_uid" id="var_uid"><!-- --></a>
<div class="evenrow">

	<div class="var-header">
		<span class="var-title">
			<span class="var-type">mixed</span>
			<span class="var-name">$uid</span>
			 = <span class="var-default"> 'bbieber2'</span>			(line <span class="line-number">31</span>)
		</span>
	</div>

	<!-- ========== Info from phpDoc block ========= -->
	<ul class="tags">
				<li><span class="field">access:</span> public</li>
			</ul>
	
	
		
		

</div>
						
		</div>
	</div>
	
	<a name="sec-methods"></a>
	<div class="info-box">
		<div class="info-box-title">Methods</div>
		<div class="nav-bar">
			<a href="#sec-description">Description</a> |
															<a href="#sec-var-summary">Vars</a> (<a href="#sec-vars">details</a>)
																	<a href="#sec-method-summary">Methods</a> (<span class="disabled">details</span>)
						
		</div>
		<div class="info-box-body">
			<a name='method_detail'></a>
<a name="methodmain" id="main"><!-- --></a>
<div class="oddrow">
	
	<div class="method-header">
		<span class="method-title">static method main</span> (line <span class="line-number">39</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Runs the test methods of this class.</p>
	<ul class="tags">
				<li><span class="field">access:</span> public</li>
			</ul>
	
	<div class="method-signature">
	    static
		<span class="method-result">void</span>
		<span class="method-name">
			main
		</span>
				()
			</div>
	
		
			
	</div>

<a name="methodsetUp" id="setUp"><!-- --></a>
<div class="evenrow">
	
	<div class="method-header">
		<span class="method-title">setUp</span> (line <span class="line-number">53</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Sets up the fixture, for example, open a network connection.</p>
<div class="description"><p>This method is called before a test is executed.</p></div>
	<ul class="tags">
				<li><span class="field">access:</span> protected</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			setUp
		</span>
				()
			</div>
	
		
			
	</div>
<a name="methodtearDown" id="tearDown"><!-- --></a>
<div class="oddrow">
	
	<div class="method-header">
		<span class="method-title">tearDown</span> (line <span class="line-number">62</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Tears down the fixture, for example, close a network connection.</p>
<div class="description"><p>This method is called after a test is executed.</p></div>
	<ul class="tags">
				<li><span class="field">access:</span> protected</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			tearDown
		</span>
				()
			</div>
	
		
			
	</div>
<a name="methodtestGetEmail" id="testGetEmail"><!-- --></a>
<div class="evenrow">
	
	<div class="method-header">
		<span class="method-title">testGetEmail</span> (line <span class="line-number">77</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Test getting the Email for a uid.</p>
	<ul class="tags">
				<li><span class="field">access:</span> public</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			testGetEmail
		</span>
				()
			</div>
	
		
			
	</div>
<a name="methodtestGetFullName" id="testGetFullName"><!-- --></a>
<div class="oddrow">
	
	<div class="method-header">
		<span class="method-title">testGetFullName</span> (line <span class="line-number">69</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
<p class="short-description">Tests getting the full name of a user.</p>
	<ul class="tags">
				<li><span class="field">access:</span> public</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			testGetFullName
		</span>
				()
			</div>
	
		
			
	</div>
<a name="methodtestGetHCard" id="testGetHCard"><!-- --></a>
<div class="evenrow">
	
	<div class="method-header">
		<span class="method-title">testGetHCard</span> (line <span class="line-number">85</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
	<ul class="tags">
				<li><span class="field">todo:</span> Implement testGetHCard().</li>
				<li><span class="field">access:</span> public</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			testGetHCard
		</span>
				()
			</div>
	
		
			
	</div>
<a name="methodtestGetVCard" id="testGetVCard"><!-- --></a>
<div class="oddrow">
	
	<div class="method-header">
		<span class="method-title">testGetVCard</span> (line <span class="line-number">94</span>)
	</div> 
	
	<!-- ========== Info from phpDoc block ========= -->
	<ul class="tags">
				<li><span class="field">todo:</span> Implement testGetVCard().</li>
				<li><span class="field">access:</span> public</li>
			</ul>
	
	<div class="method-signature">
		<span class="method-result">void</span>
		<span class="method-name">
			testGetVCard
		</span>
				()
			</div>
	
		
			
	</div>
						
		</div>
	</div>


	<p class="notes" id="credit">
		Documentation generated on Wed, 12 Aug 2009 13:00:39 -0500 by <a href="http://www.phpdoc.org" target="_blank">phpDocumentor 1.4.2</a>
	</p>
	</div>
<?php
$p->maincontentarea = ob_get_clean();
echo $p->toHtml();
?>